#!/bin/bash
set -eEu
set -o pipefail

################################################################################
# Build docker image(s). Invoke as "ci/build" from the root of the git repo.
################################################################################

. ci/functions.sh

docker-compose build
