#!/bin/bash
set -eEu
set -o pipefail

################################################################################
# Publish docker image(s). Invoke as "ci/publish" from the root of the git repo.
################################################################################

. ci/vars
. ci/functions.sh

# shellcheck disable=SC2154
docker login -u "${user}" -p "${pass}"
docker-compose -f docker-compose-metadata.yaml push
docker logout

curl -X POST 'https://hooks.microbadger.com/images/jumanjiman/rancid/QTyTWSknCxMR0T83yntDU-ubELY='
