#!/bin/bash
set -eEu
set -o pipefail

################################################################################
# Test docker image(s). Invoke as "ci/test" from the root of the git repo.
################################################################################

. ci/vars
. ci/bootstrap

echo
echo Check files for things like trailing whitespace.
pre-commit run --all-files --hook-stage manual

echo
echo Run BATS tests.
bats ci/*.bats
